### ISSUE TITLE
root required?

### ISSUE THREAD

**Issue by rcketscientist** [codekidX/storage-chooser#10]
How is this being done without `ACTION_OPEN_DOCUMENT_TREE` and `UriPermission`?  Is root required?

**Comment by codekidX** [comment]
Hey @rcketscientist, this library solely revolves around `java.io.File` class and the functionalities are built on top of the methods it provides. 

`ACTION_OPEN_DOCUMENT_TREE` and `UriPermission` are not required at all since there is no need to display various DocumentsProvider instances available on user's end.

Root is not required (and do not intend to add support) for this library but you can get `/root` files and directory path since `/root` is read-only.

**Comment by rcketscientist** [comment]
According to Google you would be blocked from writing to a folder in 5.0+ (technically 4.4, but 4.4 is broken) unless you acquire a UriPermission via ACTION_OPEN_DOCUMENT_TREE.  So how can you make use of a selected folder?

**Comment by rcketscientist** [comment]
Oh, nevermind.  I see that setting an external destination does not actually work in openGapps.  You should probably disallow that on 4.4+.

**Comment by codekidX** [comment]
@rcketscientist the crash was not due to `Uripermission` and all, it was due to animatable and I fixed it [here](https://github.com/codekidX/storage-chooser/commit/648e3905028f9886da809f5cc80274df5198c6d9) . I tested it in genymotion and all works fine now. What I cannot test was setting path from external sdcard. Can you give it a try using the new `1.0.31` release ?

**Comment by rcketscientist** [comment]
I'm not experiencing a crash.  I was simply curious if you somehow found a non-root way around SAF.  There's currently a bug in LineageOS when writing to external SD, so I can't test for a few days, but it won't work.  4.2 was the last OS that could write to external via `File`.
