### ISSUE TITLE
Unknown File

### ISSUE THREAD

**Issue by blackterminator7** [codekidX/storage-chooser#121]
I am currently developing an app to send files via bluetooth With which I am using this library to access my device. When I select a file from internal memory there is no problem the file is sent perfectly, the problem comes when selecting a file from external memory the phone sends me a message from Unknown file
Do I have to make any changes to the route that the library returns?
![Screenshot_20200626-124327_Definitivo](https://user-images.githubusercontent.com/63009837/85890649-05092f00-b7ab-11ea-9969-8f0d36875132.jpg)
![Screenshot_20200626-124253_Definitivo](https://user-images.githubusercontent.com/63009837/85890653-06d2f280-b7ab-11ea-9f9a-6b98795a12cb.jpg)

**Comment by codekidX** [comment]
Hello, this doesn't look like the error of `storage-chooser`, If your `TextView.text` has changed to the path of the file from the external storage that means the path is actually correct because [File#listFiles()](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()) is the one that returned you the path of the file. 

Please look at the implementation Bluetooth Filestream if it can read your file.
